name: Send notifications
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install web-push@3.6.7 --no-save
      - name: Send
        env:
          SB_ANON: ${{ secrets.SB_ANON }}
          PUSH_SECRET: ${{ secrets.PUSH_SECRET }}
          VAPID_PRIVATE: ${{ secrets.VAPID_PRIVATE }}
        run: node push-send.js
